[package]
name = "storybook"
version = "0.0.1"
description = "StoryBook - AI Novel Editor"
authors = ["zaizai"]
edition = "2021"
repository = "https://github.com/zzmzaizai/storybook"
homepage = "https://github.com/zzmzaizai/storybook"
license = "MIT"

[lib]
name = "storybook_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[profile.dev]
incremental = true # 以较小的步骤编译您的二进制文件。

[profile.release]
codegen-units = 1 # 允许 LLVM 执行更好的优化。
lto = true # 启用链接时优化。
opt-level = "s" # 优先考虑小的二进制文件大小。如果您更喜欢速度，请使用 `3`。
panic = "abort" # 通过禁用 panic 处理程序来提高性能。
strip = true # 确保移除调试符号。

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-opener = "2"
tauri-plugin-store = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
dirs = "5"

sea-orm = { version = "1", features = [
  "sqlx-sqlite",
  "runtime-tokio-rustls",
  "macros"
] }
anyhow = "1"
async-trait = "0.1"
toml = "0.8"
handlebars = "6"
rig-core = "0.33.0"
schemars = "1"
futures = "0.3"
reqwest = "0.13"
