use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CharacterSeed {
    pub novel_index: usize,
    pub name: String,
    pub nickname: Option<String>,
    pub age: Option<String>,
    pub personality: Option<String>,
    pub role_attribute: i32,
    pub gender: i32,
    pub character_type: i32,
    pub sort_order: i32,
}

pub fn get_character_seeds() -> Vec<CharacterSeed> {
    vec![
        CharacterSeed {
            novel_index: 0,
            name: "林远".to_string(),
            nickname: Some("船长".to_string()),
            age: Some("35".to_string()),
            personality: Some("沉稳冷静，富有领导力，在危机时刻总能做出正确的判断。对船员关怀备至，深受大家爱戴。".to_string()),
            role_attribute: 1,
            gender: 1,
            character_type: 1,
            sort_order: 1,
        },
        CharacterSeed {
            novel_index: 0,
            name: "苏晴".to_string(),
            nickname: Some("小晴".to_string()),
            age: Some("28".to_string()),
            personality: Some("聪明机智，工作能力强，是林远最得力的助手。性格开朗，善于调节气氛。".to_string()),
            role_attribute: 2,
            gender: 2,
            character_type: 1,
            sort_order: 2,
        },
        CharacterSeed {
            novel_index: 0,
            name: "张伟".to_string(),
            nickname: Some("老张".to_string()),
            age: Some("45".to_string()),
            personality: Some("飞船工程师，技术精湛。为人幽默风趣，是飞船上的开心果。".to_string()),
            role_attribute: 5,
            gender: 1,
            character_type: 1,
            sort_order: 3,
        },
        CharacterSeed {
            novel_index: 1,
            name: "陆云".to_string(),
            nickname: Some("云少".to_string()),
            age: Some("18".to_string()),
            personality: Some("天资聪颖，剑法出众。性格正直善良，嫉恶如仇。初入江湖，充满理想和热血。".to_string()),
            role_attribute: 1,
            gender: 1,
            character_type: 1,
            sort_order: 1,
        },
        CharacterSeed {
            novel_index: 1,
            name: "柳如烟".to_string(),
            nickname: Some("烟儿".to_string()),
            age: Some("17".to_string()),
            personality: Some("清风镇药铺老板的女儿，温柔善良，精通医术。与陆云偶遇后结为好友。".to_string()),
            role_attribute: 2,
            gender: 2,
            character_type: 1,
            sort_order: 2,
        },
        CharacterSeed {
            novel_index: 1,
            name: "黑风寨主".to_string(),
            nickname: Some("黑煞".to_string()),
            age: Some("40".to_string()),
            personality: Some("黑风寨的首领，心狠手辣，武功高强。是陆云遇到的第一个强敌。".to_string()),
            role_attribute: 4,
            gender: 1,
            character_type: 1,
            sort_order: 3,
        },
        CharacterSeed {
            novel_index: 2,
            name: "陈默".to_string(),
            nickname: Some("小陈".to_string()),
            age: Some("25".to_string()),
            personality: Some("普通上班族，性格内向，平时不爱说话。意外获得超能力后，开始重新审视自己的人生。".to_string()),
            role_attribute: 1,
            gender: 1,
            character_type: 1,
            sort_order: 1,
        },
        CharacterSeed {
            novel_index: 2,
            name: "林晓晓".to_string(),
            nickname: Some("晓晓".to_string()),
            age: Some("24".to_string()),
            personality: Some("陈默的同事，活泼开朗，是公司里少有的愿意主动和陈默说话的人。".to_string()),
            role_attribute: 2,
            gender: 2,
            character_type: 1,
            sort_order: 2,
        },
    ]
}
